import "std/core.sunder";

func main() void {
    var a: std::result[[:u16, :void]] = std::result[[:u16, :void]]::init_value(0xBEEF);
    dump a.is_value();
    dump a.is_error();
    dump a.value();
    dump a.error(); # boom
}
################################################################################
# 01
# 00
# EF BE
# panic: attempted to retrieve error from std::result in the `value` state
